# Generated by Django 6.0.5 on 2026-06-01 10:20

import birthdays.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Optional nickname/pet name', max_length=100)),
                ('dob', models.DateField(help_text='Date of Birth (used in URL)', unique=True)),
                ('message', models.TextField(blank=True, help_text='Personal birthday message')),
                ('song_url', models.CharField(blank=True, help_text='Direct MP3 audio URL (e.g. from Google Drive, Dropbox, etc.)', max_length=500)),
                ('song_file', models.FileField(blank=True, help_text='Or upload an MP3 file directly', null=True, upload_to='songs/')),
                ('song_name', models.CharField(blank=True, help_text='Song name to display', max_length=200)),
                ('theme_color', models.CharField(default='#e91e8c', help_text='Hex color code e.g. #ff69b4', max_length=7)),
                ('admin_password', models.CharField(help_text='Password to manage this page', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=birthdays.models.photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='birthdays.birthdayperson')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
